name: timeline_editor
description: A flutter wiidget to help you manage timelines with tracks editable or not. with move, actions...
version: 0.2.2
homepage: https://github.com/neckaros/timeline_editor

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: